spring:
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: Delate
    driver-class-name: org.postgresql.Driver
    hikari:
      allow-pool-suspension: true

  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot:
          allow_jdbc_metadata_access: false

